function scenarios = get_scenarios()
% Get the satellite orbits provided by scintpy.

%% set up Pyhton environment


% CAVEAT: you should manually set your virtual environment path which
% constains `scintpy` plus its dependencies. Otherwise, MATLAB will fail in
% running `scintpy`
% pyenv('Version', '/home/tapyu/.cache/pypoetry/virtualenvs/scintpy-ttzkkM2y-py3.12/bin/python');
pyenv('Version', '/home/felix/.cache/pypoetry/virtualenvs/scintpy-vyKKyQ8p-py3.12/bin/python');

module = py.importlib.import_module('inputs.get_scenarios');

py_out = module.get_scenarios();

scenarios(length(py_out)) = struct('sat_name', '', ...
                                   'sat_orbit', struct(), ...
                                   'receiver', struct(), ...
                                   'range_km', [], ...
                                   'time_sec', [], ...
                                   'rise_time_utc', datetime(), ...
                                   'set_time_utc', datetime());

for i=1:length(py_out)
    scenarios(i) = struct( ...
        'sat_name', string(py_out{i}{'sat_name'}), ...
        'sat_orbit', struct(py_out{i}{'sat_orbit'}), ...
        'receiver', struct(py_out{i}{'receiver'}), ...
        'range_km', double(py_out{i}{'range_km'}), ...
        'time_sec', double(py_out{i}{'time_sec'}), ...
        'rise_time_utc', py_out{i}{'rise_time_utc'}, ...
        'set_time_utc', py_out{i}{'set_time_utc'});
end

end

